name: Build Windows EXE

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Download Whisper model
      run: |
        python -c "import whisper; whisper.load_model('base')"
    
    - name: Build EXE with PyInstaller
      run: |
        pyinstaller voice_control.spec
    
    - name: Test EXE (basic check)
      run: |
        .\dist\VoiceControl\VoiceControl.exe --help
      shell: cmd
    
    - name: Package artifacts
      run: |
        Compress-Archive -Path dist\VoiceControl -DestinationPath VoiceControl-Windows.zip
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: VoiceControl-Windows
        path: VoiceControl-Windows.zip
        retention-days: 30
    
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: VoiceControl-Windows.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
